apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-1
spec:
  selector:
    app: api-gateway-1
  ports:
    - name: api-gateway-1
      port: 5000
      targetPort: 5000
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-gateway-1
spec:
  serviceName: api-gateway-service-1
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-1
  template:
    metadata:
      labels:
        app: api-gateway-1
    spec:
      containers:
        - name: api-gateway-1
          image: api-gateway:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 5000

