apiVersion: v1
kind: Service
metadata:
  name: orderdb-svc-2
spec:
  selector:
    app: orderdb-2
  ports:
    - name: orderdb-2
      port: 27017
      targetPort: 27017
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderdb-2
spec:
  serviceName: orderdb-svc-2
  replicas: 1
  selector:
    matchLabels:
      app: orderdb-2
  template:
    metadata:
      labels:
        app: orderdb-2
    spec:
      containers:
        - name: orderdb-2
          image: mongo:6
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
            name: orderdb2
          volumeMounts:
          - name: orderdb-pvc-2
            mountPath: /mnt/db
  volumeClaimTemplates:
  - metadata:
      name: orderdb-pvc-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

