apiVersion: v1
kind: Service
metadata:
  name: paymentdb-service-1
spec:
  selector:
    app: paymentdb-1
  ports:
    - name: paymentdb-1
      port: 27017
      targetPort: 27017
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paymentdb-1
spec:
  serviceName: paymentdb-service-1
  replicas: 1
  selector:
    matchLabels:
      app: paymentdb-1
  template:
    metadata:
      labels:
        app: paymentdb-1
    spec:
      containers:
        - name: paymentdb-1
          image: mongo:6
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
            name: paymentdb1
          volumeMounts:
          - name: paymentdb-pvc-1
            mountPath: /mnt/db
  volumeClaimTemplates:
  - metadata:
      name: paymentdb-pvc-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

