apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-service
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/use-regex: "true"
   nginx.ingress.kubernetes.io/rewrite-target: /$1
   nginx.ingress.kubernetes.io/configuration-snippet: |
     set $service_name "default-service";

     set_by_lua_block $service_name {
       local request_id = ngx.var.uri:match("/orders/checkout/([^/]+)")
        return "api-gateway-0";
     
       end
     }



spec:
 
 rules:
   #- host: testkube.info
   - http:
      paths:
        - path: /orders/checkout/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: nginx-ingress-controller
              port:
                number: 80
        - path: /orders/(?!checkout).+
          pathType: ImplementationSpecific
          backend:
            service:
              name: order-service
              port:
                number: 5000
        - path: /stock/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: stock-service
              port:
                number: 5000
        - path: /payment/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: payment-service
              port:
                number: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: nginx-server
  type: ExternalName
  externalName: asterios.smart.bulb.namespace.com
