apiVersion: v1
kind: Service
metadata:
  name: stockdb-service-3
spec:
  selector:
    app: stockdb-3
  ports:
    - name: stockdb-3
      port: 27017
      targetPort: 27017
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stockdb-3
spec:
  serviceName: stockdb-service-3
  replicas: 1
  selector:
    matchLabels:
      app: stockdb-3
  template:
    metadata:
      labels:
        app: stockdb-3
    spec:
      containers:
        - name: stockdb-3
          image: mongo:6
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
            name: stockdb0
          volumeMounts:
          - name: stockdb-pvc-3
            mountPath: /mnt/db
  volumeClaimTemplates:
  - metadata:
      name: stockdb-pvc-3
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

